version: '3.5'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    container_name: postgres
    volumes:
      - vcnft-postgres:/var/lib/postgresql/data
    ports:
      - '5433:5432'
    networks:
      - default

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    networks:
      - default

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vcnft-backend
    environment:
        - PORT=${PORT}
        - DB_HOST=postgres
        - DB_PORT=${POSTGRES_PORT}
        - DB_USER=${POSTGRES_USER}
        - DB_PASSWORD=${POSTGRES_PASSWORD}
        - REDIS_HOST=${REDIS_HOST}
        - REDIS_PORT=${REDIS_PORT}
    ports:
      - '3000:3000'
    networks:
      - default
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    env_file:
      - .env
    command: npm run start:dev

volumes:
  redis:
    driver: local
  vcnft-postgres:

networks:
  default:
    driver: bridge